[pytest]
pythonpath = .
addopts = --html=reports/execution_report.html --self-contained-html
testpaths = automation_framework/tests
markers =
    smoke: smoke test suite
    negative: negative test scenarios
    regression: full regression test suite